### ISSUE TITLE
Buy Command Issue.

### ISSUE THREAD

**Issue by ghost** [littlestudios69/Pika#8]
Pika responds with "Could not find [store-item] in the shop. Make sure you entered your choice case sensitive!"

This is only applies for items in the shop that have a "-" in it. For example p*buy Icead-Tea

![Screenshot_20210430-163647_Bluecord](https://user-images.githubusercontent.com/83475317/116751616-4a514b00-a9d2-11eb-9a1f-3e9f28ee0efe.jpg)

**Comment by taynotfound** [comment]
Hello Proxy,

We are currently looking into this issue and commiting a fix.

We will update this thread as soon as possible.


~ Tayron, CEO of Little Studios

VerifiedProxy ***@***.***> schrieb am Fr., 30. Apr. 2021,
10:37 PM:

**Comment by ImFelixprogram** [comment]
Hi Proxy,

the name of that item is "Iced Tea", there's no "-" inbetween.
Please try again with the correct spelling.

~ Felixprogram, CTO of Little Studios

**Comment by ImFelixprogram** [comment]
Hi @VerifiedProxy ,

after looking into it it seems like Tayron used different spellings in the shop and in the buy command.
It has been fixed with commits [bcd4baf1fdf804b6bb6fa72339397f24a000ca87](https://github.com/littlestudios69/Pika/commit/bcd4baf1fdf804b6bb6fa72339397f24a000ca87) and [f1dd77583aa87fb9cb93f6b3df32f3bc8c987a5d](https://github.com/littlestudios69/Pika/commit/f1dd77583aa87fb9cb93f6b3df32f3bc8c987a5d)

~ Felixprogram, CTO of Little Studios
